//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeSiteProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesaj
    {
        public short MesajID { get; set; }
        public string MesajGonderen { get; set; }
        public string MesajBaslik { get; set; }
        public string MesajMail { get; set; }
        public string MesajIcerik { get; set; }
    }
}
